---
name: Secret Scan

on:
  push:
  pull_request:

permissions: read-all

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with shallow clone
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
        with:
          fetch-depth: 0
      - name: Run TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown
